/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitPDefs(PDefs *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListDef(p->listdef_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDef(Def *p) {} //abstract class

void PrintAbsyn::visitDFun(DFun *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("func");
  visitId(p->id_);
  render('(');
  _i_ = 0; visitListArgument(p->listargument_);
  render(')');
  _i_ = 0; p->type_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDFunWithoutType(DFunWithoutType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("func");
  visitId(p->id_);
  render('(');
  _i_ = 0; visitListArgument(p->listargument_);
  render(')');
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDStruct(DStruct *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("type");
  visitId(p->id_);
  render("struct");
  render('{');
  _i_ = 0; visitListField(p->listfield_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDMethode(DMethode *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("func");
  render('(');
  visitId(p->id_1);
  _i_ = 0; p->type_1->accept(this);
  render(')');
  visitId(p->id_2);
  render('(');
  _i_ = 0; p->argument_->accept(this);
  render(')');
  _i_ = 0; p->type_2->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDMethodeWithoutType(DMethodeWithoutType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("func");
  render('(');
  visitId(p->id_1);
  _i_ = 0; p->type_->accept(this);
  render(')');
  visitId(p->id_2);
  render('(');
  _i_ = 0; p->argument_->accept(this);
  render(')');
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDImport(DImport *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("import");
  visitLibrary(p->library_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDPackage(DPackage *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("package");
  visitId(p->id_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListDef(ListDef *listdef)
{
  iterListDef(listdef->begin(), listdef->end());
}

void PrintAbsyn::iterListDef(ListDef::const_iterator i, ListDef::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListDef(i+1, j);
  }
}

void PrintAbsyn::visitField(Field *p) {} //abstract class

void PrintAbsyn::visitFDeclaration(FDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitId(p->id_);
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFStatment(FStatment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitId(p->id_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFStatmentMethode(FStatmentMethode *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitId(p->id_);
  render('(');
  _i_ = 0; visitListExpression(p->listexpression_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListField(ListField *listfield)
{
  iterListField(listfield->begin(), listfield->end());
}

void PrintAbsyn::iterListField(ListField::const_iterator i, ListField::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); render(';'); iterListField(i+1, j);
  }
}

void PrintAbsyn::visitArgument(Argument *p) {} //abstract class

void PrintAbsyn::visitAArgument(AArgument *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitId(p->id_);
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListArgument(ListArgument *listargument)
{
  iterListArgument(listargument->begin(), listargument->end());
}

void PrintAbsyn::iterListArgument(ListArgument::const_iterator i, ListArgument::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListArgument(i+1, j);
  }
}

void PrintAbsyn::visitStatment(Statment *p) {} //abstract class

void PrintAbsyn::visitSExprssion(SExprssion *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expression_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSDeclaration(SDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->declaration_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSSimpleStatment(SSimpleStatment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->simplestatment_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSReturn(SReturn *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("return");
  _i_ = 0; p->expression_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSReturnV(SReturnV *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("return");
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSWhile(SWhile *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("for");
  _i_ = 0; p->expression_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSFor(SFor *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("for");
  _i_ = 0; p->simplestatment_->accept(this);
  render(';');
  _i_ = 0; p->expression_1->accept(this);
  render(';');
  _i_ = 0; p->expression_2->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSForSimple(SForSimple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("for");
  _i_ = 0; p->statment_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSBlock(SBlock *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSIf(SIf *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expression_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSIfSimple(SIfSimple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->simplestatment_->accept(this);
  render(';');
  _i_ = 0; p->expression_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSIfElse(SIfElse *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expression_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_1);
  render('}');
  render("else");
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_2);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSIfElseSimple(SIfElseSimple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->simplestatment_->accept(this);
  render(';');
  _i_ = 0; p->expression_->accept(this);
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_1);
  render('}');
  render("else");
  render('{');
  _i_ = 0; visitListStatment(p->liststatment_2);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListStatment(ListStatment *liststatment)
{
  iterListStatment(liststatment->begin(), liststatment->end());
}

void PrintAbsyn::iterListStatment(ListStatment::const_iterator i, ListStatment::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListStatment(i+1, j);
  }
}

void PrintAbsyn::visitDeclaration(Declaration *p) {} //abstract class

void PrintAbsyn::visitDeclarationConstDeclaration(DeclarationConstDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->constdeclaration_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDeclarationVariableDeclaration(DeclarationVariableDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->variabledeclaration_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstDeclaration(ConstDeclaration *p) {} //abstract class

void PrintAbsyn::visitDConstant(DConstant *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("const");
  _i_ = 0; p->constspecification_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstSpecification(ConstSpecification *p) {} //abstract class

void PrintAbsyn::visitConstSpecification1(ConstSpecification1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  render('=');
  _i_ = 0; visitListExpression(p->listexpression_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstSpecification2(ConstSpecification2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  _i_ = 0; p->type_->accept(this);
  render('=');
  _i_ = 0; visitListExpression(p->listexpression_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariableDeclaration(VariableDeclaration *p) {} //abstract class

void PrintAbsyn::visitDVariable(DVariable *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("var");
  _i_ = 0; p->variablespecification_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariableSpecification(VariableSpecification *p) {} //abstract class

void PrintAbsyn::visitVariableSpecification1(VariableSpecification1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariableSpecification2(VariableSpecification2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  _i_ = 0; p->type_->accept(this);
  render('=');
  _i_ = 0; visitListExpression(p->listexpression_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariableSpecification3(VariableSpecification3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  render('=');
  _i_ = 0; visitListExpression(p->listexpression_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSimpleStatment(SimpleStatment *p) {} //abstract class

void PrintAbsyn::visitSimpleStatmentShortVariableDeclaration(SimpleStatmentShortVariableDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->shortvariabledeclaration_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitShortVariableDeclaration(ShortVariableDeclaration *p) {} //abstract class

void PrintAbsyn::visitSDVar(SDVar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListId(p->listid_);
  render(":=");
  _i_ = 0; visitListExpression(p->listexpression_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpression(Expression *p) {} //abstract class

void PrintAbsyn::visitETrue(ETrue *p)
{
  int oldi = _i_;
  if (oldi > 15) render(_L_PAREN);

  render("true");

  if (oldi > 15) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEFalse(EFalse *p)
{
  int oldi = _i_;
  if (oldi > 15) render(_L_PAREN);

  render("false");

  if (oldi > 15) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEInt(EInt *p)
{
  int oldi = _i_;
  if (oldi > 15) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 15) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEDouble(EDouble *p)
{
  int oldi = _i_;
  if (oldi > 15) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 15) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEId(EId *p)
{
  int oldi = _i_;
  if (oldi > 15) render(_L_PAREN);

  visitId(p->id_);

  if (oldi > 15) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEApp(EApp *p)
{
  int oldi = _i_;
  if (oldi > 14) render(_L_PAREN);

  visitId(p->id_);
  render('(');
  _i_ = 0; visitListExpression(p->listexpression_);
  render(')');

  if (oldi > 14) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEProj(EProj *p)
{
  int oldi = _i_;
  if (oldi > 14) render(_L_PAREN);

  _i_ = 14; p->expression_->accept(this);
  render('.');
  _i_ = 0; p->field_->accept(this);

  if (oldi > 14) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEPIncr(EPIncr *p)
{
  int oldi = _i_;
  if (oldi > 14) render(_L_PAREN);

  _i_ = 14; p->expression_->accept(this);
  render("++");

  if (oldi > 14) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEPDecr(EPDecr *p)
{
  int oldi = _i_;
  if (oldi > 14) render(_L_PAREN);

  _i_ = 14; p->expression_->accept(this);
  render("--");

  if (oldi > 14) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEIncr(EIncr *p)
{
  int oldi = _i_;
  if (oldi > 13) render(_L_PAREN);

  render("++");
  _i_ = 13; p->expression_->accept(this);

  if (oldi > 13) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEDecr(EDecr *p)
{
  int oldi = _i_;
  if (oldi > 13) render(_L_PAREN);

  render("--");
  _i_ = 13; p->expression_->accept(this);

  if (oldi > 13) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEUPlus(EUPlus *p)
{
  int oldi = _i_;
  if (oldi > 13) render(_L_PAREN);

  render('+');
  _i_ = 13; p->expression_->accept(this);

  if (oldi > 13) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEUMinus(EUMinus *p)
{
  int oldi = _i_;
  if (oldi > 13) render(_L_PAREN);

  render('-');
  _i_ = 13; p->expression_->accept(this);

  if (oldi > 13) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitENeg(ENeg *p)
{
  int oldi = _i_;
  if (oldi > 13) render(_L_PAREN);

  render('!');
  _i_ = 13; p->expression_->accept(this);

  if (oldi > 13) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitETimes(ETimes *p)
{
  int oldi = _i_;
  if (oldi > 12) render(_L_PAREN);

  _i_ = 12; p->expression_1->accept(this);
  render('*');
  _i_ = 13; p->expression_2->accept(this);

  if (oldi > 12) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEDiv(EDiv *p)
{
  int oldi = _i_;
  if (oldi > 12) render(_L_PAREN);

  _i_ = 12; p->expression_1->accept(this);
  render('/');
  _i_ = 13; p->expression_2->accept(this);

  if (oldi > 12) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEPlus(EPlus *p)
{
  int oldi = _i_;
  if (oldi > 11) render(_L_PAREN);

  _i_ = 11; p->expression_1->accept(this);
  render('+');
  _i_ = 12; p->expression_2->accept(this);

  if (oldi > 11) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEMinus(EMinus *p)
{
  int oldi = _i_;
  if (oldi > 11) render(_L_PAREN);

  _i_ = 11; p->expression_1->accept(this);
  render('-');
  _i_ = 12; p->expression_2->accept(this);

  if (oldi > 11) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitETwc(ETwc *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  _i_ = 10; p->expression_1->accept(this);
  render("<=>");
  _i_ = 11; p->expression_2->accept(this);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitELt(ELt *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  _i_ = 9; p->expression_1->accept(this);
  render('<');
  _i_ = 10; p->expression_2->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEGt(EGt *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  _i_ = 9; p->expression_1->accept(this);
  render('>');
  _i_ = 10; p->expression_2->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitELtEq(ELtEq *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  _i_ = 9; p->expression_1->accept(this);
  render("<=");
  _i_ = 10; p->expression_2->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEGtEq(EGtEq *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  _i_ = 9; p->expression_1->accept(this);
  render(">=");
  _i_ = 10; p->expression_2->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEEq(EEq *p)
{
  int oldi = _i_;
  if (oldi > 8) render(_L_PAREN);

  _i_ = 8; p->expression_1->accept(this);
  render("==");
  _i_ = 9; p->expression_2->accept(this);

  if (oldi > 8) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitENEq(ENEq *p)
{
  int oldi = _i_;
  if (oldi > 8) render(_L_PAREN);

  _i_ = 8; p->expression_1->accept(this);
  render("!=");
  _i_ = 9; p->expression_2->accept(this);

  if (oldi > 8) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEAnd(EAnd *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  _i_ = 4; p->expression_1->accept(this);
  render("&&");
  _i_ = 5; p->expression_2->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEOr(EOr *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->expression_1->accept(this);
  render("||");
  _i_ = 4; p->expression_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEAss(EAss *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 3; p->expression_1->accept(this);
  render('=');
  _i_ = 2; p->expression_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEAssadd(EAssadd *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 3; p->expression_1->accept(this);
  render("+=");
  _i_ = 2; p->expression_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEAssSub(EAssSub *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 3; p->expression_1->accept(this);
  render("-=");
  _i_ = 2; p->expression_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExpression(ListExpression *listexpression)
{
  iterListExpression(listexpression->begin(), listexpression->end());
}

void PrintAbsyn::iterListExpression(ListExpression::const_iterator i, ListExpression::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListExpression(i+1, j);
  }
}

void PrintAbsyn::visitType(Type *p) {} //abstract class

void PrintAbsyn::visitType_bool(Type_bool *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("bool");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitType_int(Type_int *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeId(TypeId *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitId(p->id_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitType_string(Type_string *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("string");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListType(ListType *listtype)
{
  iterListType(listtype->begin(), listtype->end());
}

void PrintAbsyn::iterListType(ListType::const_iterator i, ListType::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListType(i+1, j);
  }
}

void PrintAbsyn::visitListId(ListId *listid)
{
  iterListId(listid->begin(), listid->end());
}

void PrintAbsyn::iterListId(ListId::const_iterator i, ListId::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    visitId(*i);
  }
  else
  { /* cons */
    visitId(*i); render(','); iterListId(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitId(String s)
{
  render(s);
}


void PrintAbsyn::visitLibrary(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitPDefs(PDefs *p)
{
  bufAppend('(');
  bufAppend("PDefs");
  bufAppend(' ');
  bufAppend('[');
  if (p->listdef_)  p->listdef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitDef(Def *p) {} //abstract class

void ShowAbsyn::visitDFun(DFun *p)
{
  bufAppend('(');
  bufAppend("DFun");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listargument_)  p->listargument_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDFunWithoutType(DFunWithoutType *p)
{
  bufAppend('(');
  bufAppend("DFunWithoutType");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listargument_)  p->listargument_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDStruct(DStruct *p)
{
  bufAppend('(');
  bufAppend("DStruct");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listfield_)  p->listfield_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDMethode(DMethode *p)
{
  bufAppend('(');
  bufAppend("DMethode");
  bufAppend(' ');
  visitId(p->id_1);
  bufAppend(' ');
  p->type_1->accept(this);
  bufAppend(' ');
  visitId(p->id_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->argument_)  p->argument_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->type_2->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDMethodeWithoutType(DMethodeWithoutType *p)
{
  bufAppend('(');
  bufAppend("DMethodeWithoutType");
  bufAppend(' ');
  visitId(p->id_1);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitId(p->id_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->argument_)  p->argument_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDImport(DImport *p)
{
  bufAppend('(');
  bufAppend("DImport");
  bufAppend(' ');
  visitLibrary(p->library_);
  bufAppend(')');
}
void ShowAbsyn::visitDPackage(DPackage *p)
{
  bufAppend('(');
  bufAppend("DPackage");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(')');
}
void ShowAbsyn::visitListDef(ListDef *listdef)
{
  for (ListDef::const_iterator i = listdef->begin() ; i != listdef->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listdef->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitField(Field *p) {} //abstract class

void ShowAbsyn::visitFDeclaration(FDeclaration *p)
{
  bufAppend('(');
  bufAppend("FDeclaration");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFStatment(FStatment *p)
{
  bufAppend('(');
  bufAppend("FStatment");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(')');
}
void ShowAbsyn::visitFStatmentMethode(FStatmentMethode *p)
{
  bufAppend('(');
  bufAppend("FStatmentMethode");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListField(ListField *listfield)
{
  for (ListField::const_iterator i = listfield->begin() ; i != listfield->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfield->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitArgument(Argument *p) {} //abstract class

void ShowAbsyn::visitAArgument(AArgument *p)
{
  bufAppend('(');
  bufAppend("AArgument");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListArgument(ListArgument *listargument)
{
  for (ListArgument::const_iterator i = listargument->begin() ; i != listargument->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listargument->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitStatment(Statment *p) {} //abstract class

void ShowAbsyn::visitSExprssion(SExprssion *p)
{
  bufAppend('(');
  bufAppend("SExprssion");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSDeclaration(SDeclaration *p)
{
  bufAppend('(');
  bufAppend("SDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->declaration_)  p->declaration_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSSimpleStatment(SSimpleStatment *p)
{
  bufAppend('(');
  bufAppend("SSimpleStatment");
  bufAppend(' ');
  bufAppend('[');
  if (p->simplestatment_)  p->simplestatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSReturn(SReturn *p)
{
  bufAppend('(');
  bufAppend("SReturn");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSReturnV(SReturnV *p)
{
  bufAppend("SReturnV");
}
void ShowAbsyn::visitSWhile(SWhile *p)
{
  bufAppend('(');
  bufAppend("SWhile");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSFor(SFor *p)
{
  bufAppend('(');
  bufAppend("SFor");
  bufAppend(' ');
  bufAppend('[');
  if (p->simplestatment_)  p->simplestatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSForSimple(SForSimple *p)
{
  bufAppend('(');
  bufAppend("SForSimple");
  bufAppend(' ');
  bufAppend('[');
  if (p->statment_)  p->statment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSBlock(SBlock *p)
{
  bufAppend('(');
  bufAppend("SBlock");
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSIf(SIf *p)
{
  bufAppend('(');
  bufAppend("SIf");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSIfSimple(SIfSimple *p)
{
  bufAppend('(');
  bufAppend("SIfSimple");
  bufAppend(' ');
  bufAppend('[');
  if (p->simplestatment_)  p->simplestatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatment_)  p->liststatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSIfElse(SIfElse *p)
{
  bufAppend('(');
  bufAppend("SIfElse");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->liststatment_1->accept(this);
  bufAppend(' ');
  p->liststatment_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSIfElseSimple(SIfElseSimple *p)
{
  bufAppend('(');
  bufAppend("SIfElseSimple");
  bufAppend(' ');
  bufAppend('[');
  if (p->simplestatment_)  p->simplestatment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->liststatment_1->accept(this);
  bufAppend(' ');
  p->liststatment_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListStatment(ListStatment *liststatment)
{
  for (ListStatment::const_iterator i = liststatment->begin() ; i != liststatment->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != liststatment->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitDeclaration(Declaration *p) {} //abstract class

void ShowAbsyn::visitDeclarationConstDeclaration(DeclarationConstDeclaration *p)
{
  bufAppend('(');
  bufAppend("DeclarationConstDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->constdeclaration_)  p->constdeclaration_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitDeclarationVariableDeclaration(DeclarationVariableDeclaration *p)
{
  bufAppend('(');
  bufAppend("DeclarationVariableDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->variabledeclaration_)  p->variabledeclaration_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitConstDeclaration(ConstDeclaration *p) {} //abstract class

void ShowAbsyn::visitDConstant(DConstant *p)
{
  bufAppend('(');
  bufAppend("DConstant");
  bufAppend(' ');
  bufAppend('[');
  if (p->constspecification_)  p->constspecification_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitConstSpecification(ConstSpecification *p) {} //abstract class

void ShowAbsyn::visitConstSpecification1(ConstSpecification1 *p)
{
  bufAppend('(');
  bufAppend("ConstSpecification1");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitConstSpecification2(ConstSpecification2 *p)
{
  bufAppend('(');
  bufAppend("ConstSpecification2");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVariableDeclaration(VariableDeclaration *p) {} //abstract class

void ShowAbsyn::visitDVariable(DVariable *p)
{
  bufAppend('(');
  bufAppend("DVariable");
  bufAppend(' ');
  bufAppend('[');
  if (p->variablespecification_)  p->variablespecification_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVariableSpecification(VariableSpecification *p) {} //abstract class

void ShowAbsyn::visitVariableSpecification1(VariableSpecification1 *p)
{
  bufAppend('(');
  bufAppend("VariableSpecification1");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVariableSpecification2(VariableSpecification2 *p)
{
  bufAppend('(');
  bufAppend("VariableSpecification2");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVariableSpecification3(VariableSpecification3 *p)
{
  bufAppend('(');
  bufAppend("VariableSpecification3");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSimpleStatment(SimpleStatment *p) {} //abstract class

void ShowAbsyn::visitSimpleStatmentShortVariableDeclaration(SimpleStatmentShortVariableDeclaration *p)
{
  bufAppend('(');
  bufAppend("SimpleStatmentShortVariableDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->shortvariabledeclaration_)  p->shortvariabledeclaration_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitShortVariableDeclaration(ShortVariableDeclaration *p) {} //abstract class

void ShowAbsyn::visitSDVar(SDVar *p)
{
  bufAppend('(');
  bufAppend("SDVar");
  bufAppend(' ');
  bufAppend('[');
  if (p->listid_)  p->listid_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpression(Expression *p) {} //abstract class

void ShowAbsyn::visitETrue(ETrue *p)
{
  bufAppend("ETrue");
}
void ShowAbsyn::visitEFalse(EFalse *p)
{
  bufAppend("EFalse");
}
void ShowAbsyn::visitEInt(EInt *p)
{
  bufAppend('(');
  bufAppend("EInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitEDouble(EDouble *p)
{
  bufAppend('(');
  bufAppend("EDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitEId(EId *p)
{
  bufAppend('(');
  bufAppend("EId");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(')');
}
void ShowAbsyn::visitEApp(EApp *p)
{
  bufAppend('(');
  bufAppend("EApp");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEProj(EProj *p)
{
  bufAppend('(');
  bufAppend("EProj");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->field_)  p->field_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEPIncr(EPIncr *p)
{
  bufAppend('(');
  bufAppend("EPIncr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEPDecr(EPDecr *p)
{
  bufAppend('(');
  bufAppend("EPDecr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEIncr(EIncr *p)
{
  bufAppend('(');
  bufAppend("EIncr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEDecr(EDecr *p)
{
  bufAppend('(');
  bufAppend("EDecr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEUPlus(EUPlus *p)
{
  bufAppend('(');
  bufAppend("EUPlus");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEUMinus(EUMinus *p)
{
  bufAppend('(');
  bufAppend("EUMinus");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitENeg(ENeg *p)
{
  bufAppend('(');
  bufAppend("ENeg");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitETimes(ETimes *p)
{
  bufAppend('(');
  bufAppend("ETimes");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEDiv(EDiv *p)
{
  bufAppend('(');
  bufAppend("EDiv");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEPlus(EPlus *p)
{
  bufAppend('(');
  bufAppend("EPlus");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEMinus(EMinus *p)
{
  bufAppend('(');
  bufAppend("EMinus");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitETwc(ETwc *p)
{
  bufAppend('(');
  bufAppend("ETwc");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitELt(ELt *p)
{
  bufAppend('(');
  bufAppend("ELt");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEGt(EGt *p)
{
  bufAppend('(');
  bufAppend("EGt");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitELtEq(ELtEq *p)
{
  bufAppend('(');
  bufAppend("ELtEq");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEGtEq(EGtEq *p)
{
  bufAppend('(');
  bufAppend("EGtEq");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEEq(EEq *p)
{
  bufAppend('(');
  bufAppend("EEq");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitENEq(ENEq *p)
{
  bufAppend('(');
  bufAppend("ENEq");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEAnd(EAnd *p)
{
  bufAppend('(');
  bufAppend("EAnd");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEOr(EOr *p)
{
  bufAppend('(');
  bufAppend("EOr");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEAss(EAss *p)
{
  bufAppend('(');
  bufAppend("EAss");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEAssadd(EAssadd *p)
{
  bufAppend('(');
  bufAppend("EAssadd");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEAssSub(EAssSub *p)
{
  bufAppend('(');
  bufAppend("EAssSub");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitListExpression(ListExpression *listexpression)
{
  for (ListExpression::const_iterator i = listexpression->begin() ; i != listexpression->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexpression->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitType(Type *p) {} //abstract class

void ShowAbsyn::visitType_bool(Type_bool *p)
{
  bufAppend("Type_bool");
}
void ShowAbsyn::visitType_int(Type_int *p)
{
  bufAppend("Type_int");
}
void ShowAbsyn::visitTypeId(TypeId *p)
{
  bufAppend('(');
  bufAppend("TypeId");
  bufAppend(' ');
  visitId(p->id_);
  bufAppend(')');
}
void ShowAbsyn::visitType_string(Type_string *p)
{
  bufAppend("Type_string");
}
void ShowAbsyn::visitListType(ListType *listtype)
{
  for (ListType::const_iterator i = listtype->begin() ; i != listtype->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtype->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListId(ListId *listid)
{
  for (ListId::const_iterator i = listid->begin() ; i != listid->end() ; ++i)
  {
    visitId(*i) ;
    if (i != listid->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitId(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


void ShowAbsyn::visitLibrary(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}



