/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitDef(Def *t) {} //abstract class
void Skeleton::visitField(Field *t) {} //abstract class
void Skeleton::visitArgument(Argument *t) {} //abstract class
void Skeleton::visitStatment(Statment *t) {} //abstract class
void Skeleton::visitDeclaration(Declaration *t) {} //abstract class
void Skeleton::visitConstDeclaration(ConstDeclaration *t) {} //abstract class
void Skeleton::visitConstSpecification(ConstSpecification *t) {} //abstract class
void Skeleton::visitVariableDeclaration(VariableDeclaration *t) {} //abstract class
void Skeleton::visitVariableSpecification(VariableSpecification *t) {} //abstract class
void Skeleton::visitSimpleStatment(SimpleStatment *t) {} //abstract class
void Skeleton::visitShortVariableDeclaration(ShortVariableDeclaration *t) {} //abstract class
void Skeleton::visitExpression(Expression *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class

void Skeleton::visitPDefs(PDefs *p_defs)
{
  /* Code For PDefs Goes Here */

  if (p_defs->listdef_) p_defs->listdef_->accept(this);

}

void Skeleton::visitDFun(DFun *d_fun)
{
  /* Code For DFun Goes Here */

  visitId(d_fun->id_);
  if (d_fun->listargument_) d_fun->listargument_->accept(this);
  if (d_fun->type_) d_fun->type_->accept(this);
  if (d_fun->liststatment_) d_fun->liststatment_->accept(this);

}

void Skeleton::visitDFunWithoutType(DFunWithoutType *d_fun_without_type)
{
  /* Code For DFunWithoutType Goes Here */

  visitId(d_fun_without_type->id_);
  if (d_fun_without_type->listargument_) d_fun_without_type->listargument_->accept(this);
  if (d_fun_without_type->liststatment_) d_fun_without_type->liststatment_->accept(this);

}

void Skeleton::visitDStruct(DStruct *d_struct)
{
  /* Code For DStruct Goes Here */

  visitId(d_struct->id_);
  if (d_struct->listfield_) d_struct->listfield_->accept(this);

}

void Skeleton::visitDMethode(DMethode *d_methode)
{
  /* Code For DMethode Goes Here */

  visitId(d_methode->id_1);
  if (d_methode->type_1) d_methode->type_1->accept(this);
  visitId(d_methode->id_2);
  if (d_methode->argument_) d_methode->argument_->accept(this);
  if (d_methode->type_2) d_methode->type_2->accept(this);
  if (d_methode->liststatment_) d_methode->liststatment_->accept(this);

}

void Skeleton::visitDMethodeWithoutType(DMethodeWithoutType *d_methode_without_type)
{
  /* Code For DMethodeWithoutType Goes Here */

  visitId(d_methode_without_type->id_1);
  if (d_methode_without_type->type_) d_methode_without_type->type_->accept(this);
  visitId(d_methode_without_type->id_2);
  if (d_methode_without_type->argument_) d_methode_without_type->argument_->accept(this);
  if (d_methode_without_type->liststatment_) d_methode_without_type->liststatment_->accept(this);

}

void Skeleton::visitDImport(DImport *d_import)
{
  /* Code For DImport Goes Here */

  visitLibrary(d_import->library_);

}

void Skeleton::visitDPackage(DPackage *d_package)
{
  /* Code For DPackage Goes Here */

  visitId(d_package->id_);

}

void Skeleton::visitFDeclaration(FDeclaration *f_declaration)
{
  /* Code For FDeclaration Goes Here */

  visitId(f_declaration->id_);
  if (f_declaration->type_) f_declaration->type_->accept(this);

}

void Skeleton::visitFStatment(FStatment *f_statment)
{
  /* Code For FStatment Goes Here */

  visitId(f_statment->id_);

}

void Skeleton::visitFStatmentMethode(FStatmentMethode *f_statment_methode)
{
  /* Code For FStatmentMethode Goes Here */

  visitId(f_statment_methode->id_);
  if (f_statment_methode->listexpression_) f_statment_methode->listexpression_->accept(this);

}

void Skeleton::visitAArgument(AArgument *a_argument)
{
  /* Code For AArgument Goes Here */

  visitId(a_argument->id_);
  if (a_argument->type_) a_argument->type_->accept(this);

}

void Skeleton::visitSExprssion(SExprssion *s_exprssion)
{
  /* Code For SExprssion Goes Here */

  if (s_exprssion->expression_) s_exprssion->expression_->accept(this);

}

void Skeleton::visitSDeclaration(SDeclaration *s_declaration)
{
  /* Code For SDeclaration Goes Here */

  if (s_declaration->declaration_) s_declaration->declaration_->accept(this);

}

void Skeleton::visitSSimpleStatment(SSimpleStatment *s_simple_statment)
{
  /* Code For SSimpleStatment Goes Here */

  if (s_simple_statment->simplestatment_) s_simple_statment->simplestatment_->accept(this);

}

void Skeleton::visitSReturn(SReturn *s_return)
{
  /* Code For SReturn Goes Here */

  if (s_return->expression_) s_return->expression_->accept(this);

}

void Skeleton::visitSReturnV(SReturnV *s_return_v)
{
  /* Code For SReturnV Goes Here */


}

void Skeleton::visitSWhile(SWhile *s_while)
{
  /* Code For SWhile Goes Here */

  if (s_while->expression_) s_while->expression_->accept(this);
  if (s_while->liststatment_) s_while->liststatment_->accept(this);

}

void Skeleton::visitSFor(SFor *s_for)
{
  /* Code For SFor Goes Here */

  if (s_for->simplestatment_) s_for->simplestatment_->accept(this);
  if (s_for->expression_1) s_for->expression_1->accept(this);
  if (s_for->expression_2) s_for->expression_2->accept(this);
  if (s_for->liststatment_) s_for->liststatment_->accept(this);

}

void Skeleton::visitSForSimple(SForSimple *s_for_simple)
{
  /* Code For SForSimple Goes Here */

  if (s_for_simple->statment_) s_for_simple->statment_->accept(this);
  if (s_for_simple->liststatment_) s_for_simple->liststatment_->accept(this);

}

void Skeleton::visitSBlock(SBlock *s_block)
{
  /* Code For SBlock Goes Here */

  if (s_block->liststatment_) s_block->liststatment_->accept(this);

}

void Skeleton::visitSIf(SIf *s_if)
{
  /* Code For SIf Goes Here */

  if (s_if->expression_) s_if->expression_->accept(this);
  if (s_if->liststatment_) s_if->liststatment_->accept(this);

}

void Skeleton::visitSIfSimple(SIfSimple *s_if_simple)
{
  /* Code For SIfSimple Goes Here */

  if (s_if_simple->simplestatment_) s_if_simple->simplestatment_->accept(this);
  if (s_if_simple->expression_) s_if_simple->expression_->accept(this);
  if (s_if_simple->liststatment_) s_if_simple->liststatment_->accept(this);

}

void Skeleton::visitSIfElse(SIfElse *s_if_else)
{
  /* Code For SIfElse Goes Here */

  if (s_if_else->expression_) s_if_else->expression_->accept(this);
  if (s_if_else->liststatment_1) s_if_else->liststatment_1->accept(this);
  if (s_if_else->liststatment_2) s_if_else->liststatment_2->accept(this);

}

void Skeleton::visitSIfElseSimple(SIfElseSimple *s_if_else_simple)
{
  /* Code For SIfElseSimple Goes Here */

  if (s_if_else_simple->simplestatment_) s_if_else_simple->simplestatment_->accept(this);
  if (s_if_else_simple->expression_) s_if_else_simple->expression_->accept(this);
  if (s_if_else_simple->liststatment_1) s_if_else_simple->liststatment_1->accept(this);
  if (s_if_else_simple->liststatment_2) s_if_else_simple->liststatment_2->accept(this);

}

void Skeleton::visitDeclarationConstDeclaration(DeclarationConstDeclaration *declaration_const_declaration)
{
  /* Code For DeclarationConstDeclaration Goes Here */

  if (declaration_const_declaration->constdeclaration_) declaration_const_declaration->constdeclaration_->accept(this);

}

void Skeleton::visitDeclarationVariableDeclaration(DeclarationVariableDeclaration *declaration_variable_declaration)
{
  /* Code For DeclarationVariableDeclaration Goes Here */

  if (declaration_variable_declaration->variabledeclaration_) declaration_variable_declaration->variabledeclaration_->accept(this);

}

void Skeleton::visitDConstant(DConstant *d_constant)
{
  /* Code For DConstant Goes Here */

  if (d_constant->constspecification_) d_constant->constspecification_->accept(this);

}

void Skeleton::visitConstSpecification1(ConstSpecification1 *const_specification)
{
  /* Code For ConstSpecification1 Goes Here */

  if (const_specification->listid_) const_specification->listid_->accept(this);
  if (const_specification->listexpression_) const_specification->listexpression_->accept(this);

}

void Skeleton::visitConstSpecification2(ConstSpecification2 *const_specification)
{
  /* Code For ConstSpecification2 Goes Here */

  if (const_specification->listid_) const_specification->listid_->accept(this);
  if (const_specification->type_) const_specification->type_->accept(this);
  if (const_specification->listexpression_) const_specification->listexpression_->accept(this);

}

void Skeleton::visitDVariable(DVariable *d_variable)
{
  /* Code For DVariable Goes Here */

  if (d_variable->variablespecification_) d_variable->variablespecification_->accept(this);

}

void Skeleton::visitVariableSpecification1(VariableSpecification1 *variable_specification)
{
  /* Code For VariableSpecification1 Goes Here */

  if (variable_specification->listid_) variable_specification->listid_->accept(this);
  if (variable_specification->type_) variable_specification->type_->accept(this);

}

void Skeleton::visitVariableSpecification2(VariableSpecification2 *variable_specification)
{
  /* Code For VariableSpecification2 Goes Here */

  if (variable_specification->listid_) variable_specification->listid_->accept(this);
  if (variable_specification->type_) variable_specification->type_->accept(this);
  if (variable_specification->listexpression_) variable_specification->listexpression_->accept(this);

}

void Skeleton::visitVariableSpecification3(VariableSpecification3 *variable_specification)
{
  /* Code For VariableSpecification3 Goes Here */

  if (variable_specification->listid_) variable_specification->listid_->accept(this);
  if (variable_specification->listexpression_) variable_specification->listexpression_->accept(this);

}

void Skeleton::visitSimpleStatmentShortVariableDeclaration(SimpleStatmentShortVariableDeclaration *simple_statment_short_variable_declaration)
{
  /* Code For SimpleStatmentShortVariableDeclaration Goes Here */

  if (simple_statment_short_variable_declaration->shortvariabledeclaration_) simple_statment_short_variable_declaration->shortvariabledeclaration_->accept(this);

}

void Skeleton::visitSDVar(SDVar *sd_var)
{
  /* Code For SDVar Goes Here */

  if (sd_var->listid_) sd_var->listid_->accept(this);
  if (sd_var->listexpression_) sd_var->listexpression_->accept(this);

}

void Skeleton::visitETrue(ETrue *e_true)
{
  /* Code For ETrue Goes Here */


}

void Skeleton::visitEFalse(EFalse *e_false)
{
  /* Code For EFalse Goes Here */


}

void Skeleton::visitEInt(EInt *e_int)
{
  /* Code For EInt Goes Here */

  visitInteger(e_int->integer_);

}

void Skeleton::visitEDouble(EDouble *e_double)
{
  /* Code For EDouble Goes Here */

  visitDouble(e_double->double_);

}

void Skeleton::visitEId(EId *e_id)
{
  /* Code For EId Goes Here */

  visitId(e_id->id_);

}

void Skeleton::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitId(e_app->id_);
  if (e_app->listexpression_) e_app->listexpression_->accept(this);

}

void Skeleton::visitEProj(EProj *e_proj)
{
  /* Code For EProj Goes Here */

  if (e_proj->expression_) e_proj->expression_->accept(this);
  if (e_proj->field_) e_proj->field_->accept(this);

}

void Skeleton::visitEPIncr(EPIncr *ep_incr)
{
  /* Code For EPIncr Goes Here */

  if (ep_incr->expression_) ep_incr->expression_->accept(this);

}

void Skeleton::visitEPDecr(EPDecr *ep_decr)
{
  /* Code For EPDecr Goes Here */

  if (ep_decr->expression_) ep_decr->expression_->accept(this);

}

void Skeleton::visitEIncr(EIncr *e_incr)
{
  /* Code For EIncr Goes Here */

  if (e_incr->expression_) e_incr->expression_->accept(this);

}

void Skeleton::visitEDecr(EDecr *e_decr)
{
  /* Code For EDecr Goes Here */

  if (e_decr->expression_) e_decr->expression_->accept(this);

}

void Skeleton::visitEUPlus(EUPlus *eu_plus)
{
  /* Code For EUPlus Goes Here */

  if (eu_plus->expression_) eu_plus->expression_->accept(this);

}

void Skeleton::visitEUMinus(EUMinus *eu_minus)
{
  /* Code For EUMinus Goes Here */

  if (eu_minus->expression_) eu_minus->expression_->accept(this);

}

void Skeleton::visitENeg(ENeg *e_neg)
{
  /* Code For ENeg Goes Here */

  if (e_neg->expression_) e_neg->expression_->accept(this);

}

void Skeleton::visitETimes(ETimes *e_times)
{
  /* Code For ETimes Goes Here */

  if (e_times->expression_1) e_times->expression_1->accept(this);
  if (e_times->expression_2) e_times->expression_2->accept(this);

}

void Skeleton::visitEDiv(EDiv *e_div)
{
  /* Code For EDiv Goes Here */

  if (e_div->expression_1) e_div->expression_1->accept(this);
  if (e_div->expression_2) e_div->expression_2->accept(this);

}

void Skeleton::visitEPlus(EPlus *e_plus)
{
  /* Code For EPlus Goes Here */

  if (e_plus->expression_1) e_plus->expression_1->accept(this);
  if (e_plus->expression_2) e_plus->expression_2->accept(this);

}

void Skeleton::visitEMinus(EMinus *e_minus)
{
  /* Code For EMinus Goes Here */

  if (e_minus->expression_1) e_minus->expression_1->accept(this);
  if (e_minus->expression_2) e_minus->expression_2->accept(this);

}

void Skeleton::visitETwc(ETwc *e_twc)
{
  /* Code For ETwc Goes Here */

  if (e_twc->expression_1) e_twc->expression_1->accept(this);
  if (e_twc->expression_2) e_twc->expression_2->accept(this);

}

void Skeleton::visitELt(ELt *e_lt)
{
  /* Code For ELt Goes Here */

  if (e_lt->expression_1) e_lt->expression_1->accept(this);
  if (e_lt->expression_2) e_lt->expression_2->accept(this);

}

void Skeleton::visitEGt(EGt *e_gt)
{
  /* Code For EGt Goes Here */

  if (e_gt->expression_1) e_gt->expression_1->accept(this);
  if (e_gt->expression_2) e_gt->expression_2->accept(this);

}

void Skeleton::visitELtEq(ELtEq *e_lt_eq)
{
  /* Code For ELtEq Goes Here */

  if (e_lt_eq->expression_1) e_lt_eq->expression_1->accept(this);
  if (e_lt_eq->expression_2) e_lt_eq->expression_2->accept(this);

}

void Skeleton::visitEGtEq(EGtEq *e_gt_eq)
{
  /* Code For EGtEq Goes Here */

  if (e_gt_eq->expression_1) e_gt_eq->expression_1->accept(this);
  if (e_gt_eq->expression_2) e_gt_eq->expression_2->accept(this);

}

void Skeleton::visitEEq(EEq *e_eq)
{
  /* Code For EEq Goes Here */

  if (e_eq->expression_1) e_eq->expression_1->accept(this);
  if (e_eq->expression_2) e_eq->expression_2->accept(this);

}

void Skeleton::visitENEq(ENEq *en_eq)
{
  /* Code For ENEq Goes Here */

  if (en_eq->expression_1) en_eq->expression_1->accept(this);
  if (en_eq->expression_2) en_eq->expression_2->accept(this);

}

void Skeleton::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expression_1) e_and->expression_1->accept(this);
  if (e_and->expression_2) e_and->expression_2->accept(this);

}

void Skeleton::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expression_1) e_or->expression_1->accept(this);
  if (e_or->expression_2) e_or->expression_2->accept(this);

}

void Skeleton::visitEAss(EAss *e_ass)
{
  /* Code For EAss Goes Here */

  if (e_ass->expression_1) e_ass->expression_1->accept(this);
  if (e_ass->expression_2) e_ass->expression_2->accept(this);

}

void Skeleton::visitEAssadd(EAssadd *e_assadd)
{
  /* Code For EAssadd Goes Here */

  if (e_assadd->expression_1) e_assadd->expression_1->accept(this);
  if (e_assadd->expression_2) e_assadd->expression_2->accept(this);

}

void Skeleton::visitEAssSub(EAssSub *e_ass_sub)
{
  /* Code For EAssSub Goes Here */

  if (e_ass_sub->expression_1) e_ass_sub->expression_1->accept(this);
  if (e_ass_sub->expression_2) e_ass_sub->expression_2->accept(this);

}

void Skeleton::visitType_bool(Type_bool *type_bool)
{
  /* Code For Type_bool Goes Here */


}

void Skeleton::visitType_int(Type_int *type_int)
{
  /* Code For Type_int Goes Here */


}

void Skeleton::visitTypeId(TypeId *type_id)
{
  /* Code For TypeId Goes Here */

  visitId(type_id->id_);

}

void Skeleton::visitType_string(Type_string *type_string)
{
  /* Code For Type_string Goes Here */


}


void Skeleton::visitListDef(ListDef *list_def)
{
  for (ListDef::iterator i = list_def->begin() ; i != list_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListField(ListField *list_field)
{
  for (ListField::iterator i = list_field->begin() ; i != list_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArgument(ListArgument *list_argument)
{
  for (ListArgument::iterator i = list_argument->begin() ; i != list_argument->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStatment(ListStatment *list_statment)
{
  for (ListStatment::iterator i = list_statment->begin() ; i != list_statment->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExpression(ListExpression *list_expression)
{
  for (ListExpression::iterator i = list_expression->begin() ; i != list_expression->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListId(ListId *list_id)
{
  for (ListId::iterator i = list_id->begin() ; i != list_id->end() ; ++i)
  {
    visitId(*i) ;
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}

void Skeleton::visitId(Id x)
{
  /* Code for Id Goes Here */
}

void Skeleton::visitLibrary(Library x)
{
  /* Code for Library Goes Here */
}



